### ISSUE TITLE
Clarify which hosts tutorial setup are to be run on

### ISSUE THREAD

**Issue by clyne** [NCAR/NCAR-pangeo-tutorial#18]
@matt-long It would be good to clarify in the tutorial setup instructions in the readme which host is being used for each step. E.g. do you install conda on your laptop or on cheyenne?

**Comment by matt-long** [comment]
Thanks @clyne, I added the following.
>The following instructions are intended to be carried out on Cheyenne. Steps 1-3 can also be done on your laptop to install Python and associated environments there locally.
