### ISSUE TITLE
brainstorm topics for June CGD tutorial

### ISSUE THREAD

**Issue by matt-long** [NCAR/ncar-pangeo-tutorial#5]
Let's enumerate topics that deserve formal instruction at the June CGD tutorial. 

- Python basics
- git
- Python package design

**Comment by andersy005** [comment]
- Interfacing Python with Fortran/C/C++ source code

**Comment by mnlevy1981** [comment]
Is "plotting with `cartopy`" too advanced of a topic? Or would something like that / a FAQ based around "I know how to do [something] in NCL, how do I do it in python instead" be appropriate?

**Comment by matt-long** [comment]
https://python-packaging.readthedocs.io/en/latest/
